//主要数据
			var site_mainData = {
				"name": "中国电站",
				"power":"121500",
				"lv":1,
				"children": [		
					{
						"name": "广西逆变器1" ,
						"lv":2,
						"sNum":"152452ac",//序号
						"manufacturer":"growatt",//制造商
						"model":"yh1000456",//型号
						"power":"12150",
						"children": [
							{
								"name": "桂林组串",
								"lv":3,
								"model":"yh1000456",
								"children":null,
								"list":[//面板数据
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
								],
								
							}, 
							
						]
					}, 
					{
						"name": "广西逆变器1" ,
						"lv":2,
						"sNum":"152452ac",//序号
						"manufacturer":"growatt",//制造商
						"model":"yh1456",//型号
						"power":"12150",
						"children": [
							{
								"model":"yh1456",//型号
								"name": "桂林组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[//面板数据
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
								],
								
							}, 
							
						]
					}, 
					
					{
						"name": "广西逆变器1" ,
						"lv":2,
						"sNum":"152452ac",//序号
						"manufacturer":"growatt",//制造商
						"model":"yh10056",//型号
						"power":"12150",
						"children": [
							{
								"name": "桂林组串",
								"lv":3,
								"model":"yh10056",//型号
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[//面板数据
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:1,
										id:13,
										direction:0,//方向0竖向，1横向
									},
								],
								
							}, 
							
						]
					}, 
					
					{
						"name": "广西逆变器2" ,
						"lv":2,
						"sNum":"152452ac",//序号
						"manufacturer":"growatt",//制造商
						"model":"yh1000456",//型号
						"power":"2150",
						"children": [
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
							
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:2,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
							
							{
								"name": "柳州组串",
								"lv":3,
								"children":[
									{
										"name": "",
										"lv":4,
									}
								],
								"list":[
									{
										name:"绝望的面板1",
										sNum:"1",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.0",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:11,
										direction:0,//方向0竖向，1横向
										
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:12,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:13,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2",
										sNum:"2",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:14,
										direction:0,//方向0竖向，1横向
									},
									{
										name:"绝望的面板2sdf",
										sNum:"3",//序号
										manufacturer:"growatt",//制造商
										model:"1.0.00",//型号
										optimizerV:123,//优化器电压
										power:15,//功率
										voltage:220,//电压
										electricity:120,//电流
										status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
										string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
										pid:2,
										id:15,
										direction:0,//方向0竖向，1横向
									},
								],
							},
						]
					}, 
					
					
					
				]
			};
			
			