//其他参数，x,y分别代表图形在svg上的位置，w,h代表宽高
var site_data = {
	name:"深圳宝安电站",
	power:"121500",
	inverter:[//逆变器
		{
			name:"逆变器1号",
			id:1,
			sNum:"152452ac",//序号
			manufacturer:"growatt",//制造商
			model:"yh1000456",//型号
			power:"12150",
			panelList:[
				{
					name:"绝望的面板1",
					sNum:"xhb001",//序号
					manufacturer:"growatt",//制造商
					model:"mmp001",//型号
					optimizerV:123,//优化器电压
					power:150,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:11,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2",
					sNum:"xhb002",//序号
					manufacturer:"growatt",//制造商
					model:"mmp002",//型号
					optimizerV:123,//优化器电压
					power:115,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:12,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2sdf",
					sNum:"xhb003",//序号
					manufacturer:"growatt",//制造商
					model:"mmp003",//型号
					optimizerV:123,//优化器电压
					power:154,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:13,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的面板2",
					sNum:"xhb004",//序号
					manufacturer:"growatt",//制造商
					model:"mmp004",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:14,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb005",//序号
					manufacturer:"growatt",//制造商
					model:"mmp005",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:15,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb006",//序号
					manufacturer:"growatt",//制造商
					model:"mmp006",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:16,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb007",//序号
					manufacturer:"growatt",//制造商
					model:"mmp007",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:2,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:17,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb008",//序号
					manufacturer:"growatt",//制造商
					model:"mmp008",//型号
					optimizerV:123,//优化器电压
					power:5,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:3,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:18,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板1",
					sNum:"xhb009",//序号
					manufacturer:"growatt",//制造商
					model:"mmp009",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:5,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:19,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				
				{
					name:"绝望sdf的面板2",
					sNum:"xhb010",//序号
					manufacturer:"growatt",//制造商
					model:"mmp010",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:22,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb011",//序号
					manufacturer:"growatt",//制造商
					model:"mmp011",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:23,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb012",//序号
					manufacturer:"growatt",//制造商
					model:"mmp012",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:24,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb013",//序号
					manufacturer:"growatt",//制造商
					model:"mmp013",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:2,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:25,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sf的板2",
					sNum:"xhb074",//序号
					manufacturer:"growatt",//制造商
					model:"mmp074",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:2,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:125,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb075",//序号
					manufacturer:"growatt",//制造商
					model:"mmp075",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:2,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:1,
					id:225,
					direction:1,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
			]
		},
		{
			name:"逆变器24号",
			id:2,
			power:"150",
			sNum:"152452ad",//序号
			manufacturer:"growatt",//制造商
			model:"1212xhb",//型号
			panelList:[
				{
					name:"绝望的面板1",
					sNum:"xhb014",//序号
					manufacturer:"growatt",//制造商
					model:"mmp014",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:27,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2",
					sNum:"xhb015",//序号
					manufacturer:"growatt",//制造商
					model:"mmp015",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:28,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2sdf",
					sNum:"xhb016",//序号
					manufacturer:"growatt",//制造商
					model:"mmp016",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:29,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的面板2",
					sNum:"xhb017",//序号
					manufacturer:"growatt",//制造商
					model:"mmp017",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:30,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb018",//序号
					manufacturer:"growatt",//制造商
					model:"mmp018",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:31,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望sdf的板2",
					sNum:"xhb019",//序号
					manufacturer:"growatt",//制造商
					model:"mmp019",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:1,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:2,
					id:32,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				
			]
		},
		{
			name:"逆变器2号",
			id:3,
			power:"50",
			sNum:"152452aoe",//序号
			manufacturer:"growatt",//制造商
			model:"tuy120",//型号
			panelList:[
				{
					name:"绝望的面板1",
					sNum:"xhb020",//序号
					manufacturer:"growatt",//制造商
					model:"mmp020",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:1,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:3,
					id:34,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2",
					sNum:"xhb021",//序号
					manufacturer:"growatt",//制造商
					model:"mmp021",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:0,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:3,
					id:35,
					direction:0,//方向0竖向，1横向
					angle:180,//角度（顺时针，指北）
				},
				{
					name:"绝望的面板2sdf",
					sNum:"xhb022",//序号
					manufacturer:"growatt",//制造商
					model:"mmp022",//型号
					optimizerV:123,//优化器电压
					power:15,//功率
					voltage:220,//电压
					electricity:120,//电流
					status:0,//（0，1，2，3分别代表在线，离线，发电异常，无优化器）
					string:2,//所属组串，0代表不属于组串的，同样的数据其他值相同为同一组组串
					pid:3,
					id:36,
					direction:0,//方向0竖向，1横向
					angle:45,//角度（顺时针，指北）
				},
				
			]
		},
	]
}

localStorage.setItem("site_data",JSON.stringify(site_data));